/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wdzwilcfjxtoufrypenx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkendpbGNmanh0b3VmcnlwZW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NDczMzQsImV4cCI6MjA4NzEyMzMzNH0.j8eZW79moI0vY0lywdI09L-MeQt6DRQ7-l-bjd4ssiE"