#!/usr/bin/env python3
import re
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

SRC = Path('/Users/arunodhaiv/Downloads/Stories_De_Cafe_Menu.xlsx')
OUT = Path('/Users/arunodhaiv/Desktop/SDC/sql/import_stories_menu.sql')
NS = {'a': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}


def col_index(ref: str) -> int:
    m = re.match(r'([A-Z]+)', ref)
    s = m.group(1)
    n = 0
    for ch in s:
        n = n * 26 + (ord(ch) - 64)
    return n - 1


def parse_rows(path: Path):
    z = zipfile.ZipFile(path)
    root = ET.fromstring(z.read('xl/worksheets/sheet1.xml'))
    rows = []
    for row in root.findall('.//a:sheetData/a:row', NS):
        cells = {}
        for c in row.findall('a:c', NS):
            idx = col_index(c.attrib.get('r', 'A1'))
            t = c.attrib.get('t')
            if t == 'inlineStr':
                value = ''.join(tn.text or '' for tn in c.findall('.//a:t', NS)).strip()
            else:
                value = (c.findtext('a:v', default='', namespaces=NS) or '').strip()
            cells[idx] = value
        max_idx = max(cells.keys()) if cells else -1
        arr = [cells.get(i, '') for i in range(max(7, max_idx + 1))]
        rows.append(arr[:7])
    return rows


def esc(s: str) -> str:
    return s.replace("'", "''")


def main():
    if not SRC.exists():
        raise SystemExit(f'File not found: {SRC}')

    rows = parse_rows(SRC)
    if not rows or rows[0][:3] != ['Category', 'Item', 'Price']:
        raise SystemExit('Unexpected sheet format')

    menu_rows = rows[1:]
    categories = []
    seen = set()
    items = []

    for r in menu_rows:
        category, item, price, full, half, qtr, notes = [x.strip() for x in r]
        if not category or not item:
            continue

        if category not in seen:
            categories.append(category)
            seen.add(category)

        if price:
            items.append((category, item, float(price), notes))

        # If there are size-wise prices, create explicit variant items.
        if full:
            items.append((category, f"{item} (Full)", float(full), notes))
        if half:
            items.append((category, f"{item} (Half)", float(half), notes))
        if qtr:
            items.append((category, f"{item} (Qtr)", float(qtr), notes))

    lines = []
    lines.append('-- Auto-generated from Stories_De_Cafe_Menu.xlsx')
    lines.append('-- Generated by scripts/generate_menu_sql.py')
    lines.append('')
    lines.append('begin;')
    lines.append('')

    for c in categories:
        lines.append(f"insert into categories (name) values ('{esc(c)}') on conflict (name) do nothing;")

    lines.append('')

    for category, name, price, notes in items:
        desc = notes if notes else ''
        lines.append(
            "insert into menu_items (category_id, name, price, description, is_available) "
            f"select c.id, '{esc(name)}', {price:.2f}, '{esc(desc)}', true from categories c where c.name = '{esc(category)}' "
            "and not exists (select 1 from menu_items mi where mi.category_id = c.id and mi.name = '"
            f"{esc(name)}');"
        )

    lines.append('')
    lines.append('commit;')
    lines.append('')
    lines.append('-- Rows summary')
    lines.append(f'-- Categories: {len(categories)}')
    lines.append(f'-- Menu items: {len(items)}')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT}')
    print(f'Categories: {len(categories)}')
    print(f'Items: {len(items)}')


if __name__ == '__main__':
    main()
